In [3]:
import tensorflow as tf
print(tf.__version__)


2.9.2


In [ ]:
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
scalar.ndim

0

In [ ]:
tensor = tf.constant(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ],
     
        [
            [10, 11, 12],
            [13, 14, 15],
            [16, 17, 18]
        ],
     
        [
            [19, 20, 21],
            [22, 23, 24],
            [25, 26, 27]
        ]
    ]
)

tensor.ndim

3

In [ ]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
random_1 = tf.random.normal(shape=(5, 1))
random_2 = tf.random.uniform(shape=(5,1))
print(random_1)
print(random_2)

tf.Tensor(
[[ 1.4046352 ]
 [ 0.9842087 ]
 [ 0.3452449 ]
 [ 0.26993352]
 [-0.8831093 ]], shape=(5, 1), dtype=float32)
tf.Tensor(
[[0.5598538 ]
 [0.48030972]
 [0.26172185]
 [0.07559991]
 [0.7793882 ]], shape=(5, 1), dtype=float32)


In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[10, 7], [50, 2], [3, 5]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [50,  2],
       [ 3,  5]], dtype=int32)>

In [ ]:
# Shuffle tensor
shuffled = tf.random.shuffle(not_shuffled);

shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[50,  2],
       [10,  7],
       [ 3,  5]], dtype=int32)>

In [ ]:
print(tf.ones((10, 7)))

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]], shape=(10, 7), dtype=float32)


In [ ]:
print(tf.zeros((5, 5)))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [6]:
import numpy as np

np_A = np.arange(1, 25, dtype=np.int32)

np_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(np_A, shape=(2, 3, 4))
B = tf.constant(np_A)

A, B, A.numpy()

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32))

In [7]:
matrix = tf.Variable(np.arange(4).reshape((2, 2)))
matrix, matrix[:, -1]

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
 array([[0, 1],
        [2, 3]])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 3])>)

In [1]:
matrix, matrix[..., tf.newaxis], matrix[:, tf.newaxis, :]

NameError: ignored

In [9]:
matrix, tf.expand_dims(matrix, axis=-1), tf.expand_dims(matrix, axis=0), tf.expand_dims(matrix, axis=1)

(<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
 array([[0, 1],
        [2, 3]])>, <tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
 array([[[0],
         [1]],
 
        [[2],
         [3]]])>, <tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
 array([[[0, 1],
         [2, 3]]])>, <tf.Tensor: shape=(2, 1, 2), dtype=int64, numpy=
 array([[[0, 1]],
 
        [[2, 3]]])>)

In [12]:
tf.expand_dims(tf.constant([1, 2, 3, 4]), axis=-1)

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [ ]:
tensor = tf.constant([[15, 2], [64, 1]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 12],
       [74, 11]], dtype=int32)>

It is better to use tf.multiply instead of * sign to increase speed of our program

In [ ]:
tf.math.subtract(tensor, 10), tf.math.multiply(tensor, 2), tf.math.divide(tensor, 2), tf.math.add(tensor, 2)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5, -8],
        [54, -9]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 30,   4],
        [128,   2]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[ 7.5,  1. ],
        [32. ,  0.5]])>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[17,  4],
        [66,  3]], dtype=int32)>)

In [ ]:
A = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
B = tf.constant([[3, 5], [6, 7], [1, 8]])

tf.matmul(A, B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
B = tf.constant([1.7, 7.4])
C = tf.constant([5, 10])

B.dtype, C.dtype

(tf.float32, tf.int32)

In [ ]:
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Aggregation
A = tf.constant([[-1, 2, 3], [4, -6, 7], [7, -8, 9]])

tf.abs(A)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 6, 7],
       [7, 8, 9]], dtype=int32)>

In [ ]:
import numpy as np

E = tf.constant(np.random.randint(0, 100, size=50))

print(tf.reshape(E, (10, 5)))
print(tf.reduce_min(E))
print(tf.reduce_max(E))
print(tf.reduce_mean(E))
print(tf.reduce_sum(E))

print(tf.math.reduce_variance(tf.cast(E, dtype=tf.float32)))
print(tf.math.reduce_std(tf.cast(E, dtype=tf.float32)))

tf.Tensor(
[[44 19 23 72  8]
 [37 44 92 34 58]
 [ 6 52 20  3 12]
 [61 90 57 77 91]
 [83 89 74 83 90]
 [58 88 85 53 97]
 [94 33 47 63 16]
 [62 80 62 81 99]
 [ 1 28 96 61 15]
 [13 23 93 54 93]], shape=(10, 5), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(99, shape=(), dtype=int64)
tf.Tensor(56, shape=(), dtype=int64)
tf.Tensor(2814, shape=(), dtype=int64)
tf.Tensor(921.1616, shape=(), dtype=float32)
tf.Tensor(30.350645, shape=(), dtype=float32)


# Example of Standard Deviation

Say we have the data points 5, 7, 3, and 7, which total 22. You would then divide 22 by the number of data points, in this case, four—resulting in a mean of 5.5. This leads to the following determinations: x̄ = 5.5 and N = 4.

The variance is determined by subtracting the mean's value from each data point, resulting in -0.5, 1.5, -2.5, and 1.5. Each of those values is then squared, resulting in 0.25, 2.25, 6.25, and 2.25. The square values are then added together, giving a total of 11, which is then divided by the value of N minus 1, which is 3, resulting in a variance of approximately 3.67.

The square root of the variance is then calculated, which results in a standard deviation measure of approximately 1.915.

https://www.investopedia.com/terms/s/standarddeviation.asp#toc-example-of-standard-deviation

In [ ]:
import tensorflow_probability as tfp

print(tfp.stats.variance(E))
print(tfp.stats.stddev(tf.cast(E, dtype=tf.float32)))

# tf.math.reduce_std(tf.cast(E, dtype=tf.float32)) == tfp.stats.stddev(tf.cast(E, dtype=tf.float32))
# tfp.stats.variance(E) == tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

tf.Tensor(714, shape=(), dtype=int64)
tf.Tensor(26.72901, shape=(), dtype=float32)
tf.Tensor(26.72901, shape=(), dtype=float32)


In [ ]:
# Sorting

mat = [[3,2,1],
       [2,1,3],
       [1,3,2]]

tf.sort(mat, axis=-1).numpy()  

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
tf.argmax(F), tf.reduce_max(F)


(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [ ]:
# Squeeze tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))

G_squeezed = tf.squeeze(G)
G_squeezed.shape


TensorShape([50])

In [ ]:
a = [0, 1, 2, 3]

tf.one_hot(a, depth=4), tf.one_hot(a, depth=4, on_value="Hello World", off_value="0")

(<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=string, numpy=
 array([[b'Hello World', b'0', b'0', b'0'],
        [b'0', b'Hello World', b'0', b'0'],
        [b'0', b'0', b'Hello World', b'0'],
        [b'0', b'0', b'0', b'Hello World']], dtype=object)>)

In [ ]:
H = tf.range(1, 10)

print(tf.square(H))
print(tf.math.sqrt(tf.cast(H, dtype=tf.float32)))

tf.Tensor([ 1  4  9 16 25 36 49 64 81], shape=(9,), dtype=int32)
tf.Tensor(
[1.        1.4142135 1.7320508 2.        2.236068  2.4494898 2.6457512
 2.828427  3.       ], shape=(9,), dtype=float32)


In [ ]:
tf.math.log(tf.math.sqrt(tf.cast(H, dtype=tf.float32)))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.        , 0.3465736 , 0.54930615, 0.6931472 , 0.804719  ,
       0.89587975, 0.9729551 , 1.0397208 , 1.0986123 ], dtype=float32)>

In [ ]:
B = tf.constant([1.23, 2.564, 4.454, 5.])

print(tf.round(B))
print(tf.sigmoid(B))
print(tf.math.top_k(B, k=2).indices)

tf.Tensor([1. 3. 4. 5.], shape=(4,), dtype=float32)
tf.Tensor([0.7738186 0.9285084 0.9885018 0.9933072], shape=(4,), dtype=float32)
tf.Tensor([3 2], shape=(2,), dtype=int32)


In [ ]:
numpy_J = np.array([3., 2., 1., 7.])
tensor_J = tf.constant([3., 78., 7., 2.])

numpy_J.dtype, tensor_J.dtype

(dtype('float64'), tf.float32)

In [ ]:
# Get GPU device
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Tue Dec 27 08:07:49 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
A = tf.random.uniform([5, 300], minval=0, maxval=1)
A.shape

TensorShape([5, 300])